// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const usaPostgres = (process.env.DATABASE_URL ?? "").startsWith("postgres");

export default defineConfig({
  schema: usaPostgres ? "prisma/schema.postgresql.prisma" : "prisma/schema.prisma",
  migrations: {
    path: usaPostgres ? "prisma/migrations-postgresql" : "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
