import { Prisma } from "@prisma/client";

function diasAtras(n: number, hora = "16:30") {
  const d = new Date();
  d.setDate(d.getDate() - n);
  const [h, m] = hora.split(":").map(Number);
  d.setHours(h, m, 0, 0);
  return d;
}

type OperacaoSeed = Omit<Prisma.OperacaoCreateInput, "id" | "createdAt" | "updatedAt">;

export function gerarOperacoesExemplo(): OperacaoSeed[] {
  return [
    {
      data: diasAtras(28),
      liga: "Brasileirão Série A",
      timeCasa: "Flamengo",
      timeFora: "Palmeiras",
      mercado: "Resultado Final",
      metodo: "Lay Empate",
      tipo: "Lay",
      momento: "Pré-jogo",
      oddEntrada: 3.4,
      stake: 4,
      responsabilidade: 9.6,
      resultado: "Green",
      lucro: 4,
      observacoes: "Empate saiu de cena no 2ºT, lay coberto antes do apito final.",
    },
    {
      data: diasAtras(27),
      liga: "Premier League",
      timeCasa: "Arsenal",
      timeFora: "Chelsea",
      mercado: "Próximo Gol",
      metodo: "Scalping Ao Vivo",
      tipo: "Trade",
      momento: "22' 1ºT",
      oddEntrada: 2.1,
      oddSaida: 1.85,
      stake: 6,
      resultado: "Green",
      lucro: 0.86,
      observacoes: "Pressão do Arsenal, saída rápida no movimento de odd.",
    },
    {
      data: diasAtras(26),
      liga: "La Liga",
      timeCasa: "Real Madrid",
      timeFora: "Sevilla",
      mercado: "Over/Under 2.5",
      metodo: "Pressão Reversa",
      tipo: "Back",
      momento: "Pré-jogo",
      oddEntrada: 1.95,
      stake: 5,
      resultado: "Green",
      lucro: 4.75,
    },
    {
      data: diasAtras(25),
      liga: "Serie A",
      timeCasa: "Inter",
      timeFora: "Milan",
      mercado: "Resultado Final",
      metodo: "Lay Empate",
      tipo: "Lay",
      momento: "Pré-jogo",
      oddEntrada: 3.2,
      stake: 4,
      responsabilidade: 8.8,
      resultado: "Red",
      lucro: -8.8,
      observacoes: "Jogo travado, empate persistiu até o fim.",
    },
    {
      data: diasAtras(24),
      liga: "Bundesliga",
      timeCasa: "Bayern de Munique",
      timeFora: "Dortmund",
      mercado: "Próximo Gol",
      metodo: "Cash Out Verde",
      tipo: "Trade",
      momento: "61' 2ºT",
      oddEntrada: 1.7,
      oddSaida: 1.4,
      stake: 8,
      resultado: "Green",
      lucro: 1.71,
    },
    {
      data: diasAtras(22),
      liga: "Ligue 1",
      timeCasa: "PSG",
      timeFora: "Marselha",
      mercado: "Handicap Asiático",
      metodo: "Pressão Reversa",
      tipo: "Back",
      momento: "Pré-jogo",
      oddEntrada: 1.88,
      stake: 5,
      resultado: "Green",
      lucro: 4.4,
    },
    {
      data: diasAtras(20),
      liga: "Brasileirão Série A",
      timeCasa: "Corinthians",
      timeFora: "São Paulo",
      mercado: "Resultado Final",
      metodo: "Lay Empate",
      tipo: "Lay",
      momento: "Pré-jogo",
      oddEntrada: 3.1,
      stake: 4,
      responsabilidade: 8.4,
      resultado: "Green",
      lucro: 4,
    },
    {
      data: diasAtras(19),
      liga: "Premier League",
      timeCasa: "Man City",
      timeFora: "Liverpool",
      mercado: "Próximo Gol",
      metodo: "Scalping Ao Vivo",
      tipo: "Trade",
      momento: "10' 1ºT",
      oddEntrada: 2.5,
      oddSaida: 2.9,
      stake: 5,
      resultado: "Red",
      lucro: -0.69,
      observacoes: "Movimento contrário, saída no stop.",
    },
    {
      data: diasAtras(17),
      liga: "La Liga",
      timeCasa: "Atlético de Madrid",
      timeFora: "Barcelona",
      mercado: "Resultado Final",
      metodo: "Lay Empate",
      tipo: "Lay",
      momento: "Pré-jogo",
      oddEntrada: 3.5,
      stake: 4,
      responsabilidade: 10,
      resultado: "Green",
      lucro: 4,
    },
    {
      data: diasAtras(15),
      liga: "Serie A",
      timeCasa: "Juventus",
      timeFora: "Napoli",
      mercado: "Over/Under 2.5",
      metodo: "Pressão Reversa",
      tipo: "Back",
      momento: "Pré-jogo",
      oddEntrada: 2.05,
      stake: 5,
      resultado: "Anulado",
      lucro: 0,
      observacoes: "Jogo cancelado por chuva, stake devolvida.",
    },
    {
      data: diasAtras(13),
      liga: "Bundesliga",
      timeCasa: "Leverkusen",
      timeFora: "RB Leipzig",
      mercado: "Próximo Gol",
      metodo: "Cash Out Verde",
      tipo: "Trade",
      momento: "75' 2ºT",
      oddEntrada: 1.6,
      oddSaida: 1.3,
      stake: 7,
      resultado: "Green",
      lucro: 1.62,
    },
    {
      data: diasAtras(11),
      liga: "Brasileirão Série A",
      timeCasa: "Grêmio",
      timeFora: "Internacional",
      mercado: "Resultado Final",
      metodo: "Lay Empate",
      tipo: "Lay",
      momento: "Pré-jogo",
      oddEntrada: 3.3,
      stake: 4,
      responsabilidade: 9.2,
      resultado: "Red",
      lucro: -9.2,
    },
    {
      data: diasAtras(9),
      liga: "Ligue 1",
      timeCasa: "Lyon",
      timeFora: "Monaco",
      mercado: "Handicap Asiático",
      metodo: "Pressão Reversa",
      tipo: "Back",
      momento: "Pré-jogo",
      oddEntrada: 1.92,
      stake: 5,
      resultado: "Green",
      lucro: 4.6,
    },
    {
      data: diasAtras(6),
      liga: "Premier League",
      timeCasa: "Tottenham",
      timeFora: "Newcastle",
      mercado: "Próximo Gol",
      metodo: "Scalping Ao Vivo",
      tipo: "Trade",
      momento: "33' 1ºT",
      oddEntrada: 2.3,
      oddSaida: 1.95,
      stake: 6,
      resultado: "Green",
      lucro: 1.08,
    },
    {
      data: diasAtras(3),
      liga: "La Liga",
      timeCasa: "Valencia",
      timeFora: "Betis",
      mercado: "Resultado Final",
      metodo: "Lay Empate",
      tipo: "Lay",
      momento: "Pré-jogo",
      oddEntrada: 3.15,
      stake: 4,
      responsabilidade: 8.6,
      resultado: "Green",
      lucro: 4,
    },
    {
      data: diasAtras(1),
      liga: "Serie A",
      timeCasa: "Roma",
      timeFora: "Lazio",
      mercado: "Próximo Gol",
      metodo: "Cash Out Verde",
      tipo: "Trade",
      momento: "55' 2ºT",
      oddEntrada: 1.75,
      oddSaida: 1.5,
      stake: 7,
      resultado: "Green",
      lucro: 1.17,
    },
  ];
}
